services:
  device_01:
    env_file:
      - webapp.env
    build:
      context: .
    environment:
      DEVICE_NAME: device-01
      DEVICE_LOCATION: "Building A - Floor 1"
    ports:
      - "8001:8000"

  device_02:
    env_file:
      - webapp.env
    build:
      context: .
    environment:
      DEVICE_NAME: device-02
      DEVICE_LOCATION: "Building A - Floor 2"
    ports:
      - "8002:8000"

  device_03:
    env_file:
      - webapp.env
    build:
      context: .
    environment:
      DEVICE_NAME: device-03
      DEVICE_LOCATION: "Building B - Floor 1"
    ports:
      - "8003:8000"

